//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1 {
    
    
    public partial class ArchivistePanel {
        
        /// <summary>
        /// archivisteID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField archivisteID;
        
        /// <summary>
        /// alertRequestSuccess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel alertRequestSuccess;
        
        /// <summary>
        /// alertSuccessText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertSuccessText;
        
        /// <summary>
        /// ArchiveCote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ArchiveCote;
        
        /// <summary>
        /// StatusList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList StatusList;
        
        /// <summary>
        /// ModifyStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ModifyStatus;
        
        /// <summary>
        /// HiddenField1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HiddenField1;
        
        /// <summary>
        /// ModalAjouter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ModalAjouter;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new WebApplication1.SiteMaster Master {
            get {
                return ((WebApplication1.SiteMaster)(base.Master));
            }
        }
    }
}
